version: '3.4'
services:
  node:
    container_name: node
    image: node:18-alpine
    working_dir: /var/www/html/app/
    user: node
    volumes:
      - ./Fundify-Back:/var/www/html/app/
    ports:
      - "1337:1337"
    tty: true
    stdin_open: true
    command: sh -c "yarn && yarn dev"
    networks:
      - my_network
      - my_network2

  psp:
    container_name: psp
    image: node:18-alpine
    working_dir: /var/www/html/app/
    user: node
    volumes:
      - ./Fundify-Back/pspServer:/var/www/html/app/
    ports:
      - "1338:1338"
    tty: true
    command: sh -c "yarn && yarn dev"
    networks:
      - my_network

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: nodejs
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - my_network2

  adminer:
    image: adminer
    depends_on:
      - database
    ports:
      - "8080:808"
    environment:
      POSTGRES_USER: nodejs
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_DB: app
    networks:
      - my_network2

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nhisty/dist:/usr/share/nginx/html
      - ./Fundify-Front/dist:/usr/share/nginx/html/merchant
      - ./nhisty/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
      - ./nhistywildcare.key:/etc/nginx/nhistywildcare.key
      - ./Fundify-Front/dist:/usr/share/nginx/front
      - ./Fundify-Back/:/usr/share/nginx/back
      - ./Fundify-Back/pspServer:/usr/share/nginx/pspServer
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - my_network
      - my_network2

volumes:
  db_data:

networks:
  my_network: ~
  my_network2: ~
